import fs from 'node:fs';
import assert from 'node:assert/strict';
import {test} from 'node:test';
import {PGlite} from '@electric-sql/pglite';
test('035 automation migration: immutable sources, history, atomic save, private evidence, parent cycles and RLS',async()=>{
 const db=new PGlite(); const admin='00000000-0000-4000-8000-000000000001',fan='00000000-0000-4000-8000-000000000002';
 try {
 const fixture=fs.readFileSync(new URL('./events.test.js',import.meta.url),'utf8');
 await db.exec(fixture.match(/await db\.exec\(`([\s\S]*?)`\)/)[1].replaceAll('${admin}',admin).replaceAll('${fan}',fan));
 const wechat=fs.readFileSync(new URL('./fixtures/automation-wechat-setup.txt',import.meta.url),'utf8');
 const extra=wechat.match(/await db\.exec\(`([\s\S]*?)`\);/)[1].replaceAll('${fan}',fan).replaceAll('${other}','00000000-0000-4000-8000-000000000009');
 await db.exec(extra);
 for(const name of ['004_event_form_import.sql','006_community.sql','007_task_categories.sql','009_activity_categories.sql','012_group_save_display.sql','013_artist_selection.sql','014_activity_labels.sql','015_scheduling_import_drafts.sql','016_event_updates_and_details.sql','017_event_bulk_management.sql','018_backend_access_approval.sql','019_editor_permissions.sql','020_fashion_week.sql','021_announcement_deletion.sql','022_artist_participation_corrections.sql','023_invitation_participation.sql'])await db.exec(fs.readFileSync(new URL('../supabase/'+name,import.meta.url),'utf8'));
 await db.exec(fs.readFileSync(new URL('../supabase/025_activity_dates_display.sql',import.meta.url),'utf8'));
 await db.exec(fs.readFileSync(new URL('../supabase/030_event_trash.sql',import.meta.url),'utf8'));
 await db.exec("create function chob_private.is_wechat_session() returns boolean language sql stable as $$select coalesce(current_setting('test.wechat',true),'false')='true'$$; create table public.chob_submission_reviews(event_id uuid); insert into participation_conditions values(gen_random_uuid(),'ticket','购票'); insert into artists(id,name) values('00000000-0000-4000-8000-000000000010','A');");
 const sql=fs.readFileSync(new URL('../supabase/034_provenance_entities.sql',import.meta.url),'utf8');await db.exec(sql);await db.exec(sql);const autoSql=fs.readFileSync(new URL('../supabase/035_automation.sql',import.meta.url),'utf8');await db.exec(autoSql);await db.exec(autoSql);
 async function as(id,role='authenticated'){await db.exec('reset role;set role '+role);await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id||'']);}
 const call=async(name,args=[])=>(await db.query('select '+name+'('+args.map((_,i)=>'$'+(i+1)).join(',')+') as result',args)).rows[0].result;
 await as(admin);
 const source={url:'https://example.org/official',source_type:'organizer',priority:1,raw_evidence:{text:'Official show announcement'}};
 const sid=await call('chob_add_source',[source]);assert.equal(await call('chob_add_source',[source]),sid);
 const sid2=await call('chob_add_source',[{...source,raw_evidence:{text:'Official show updated'}}]);assert.notEqual(sid,sid2);
 await call('chob_verify_source',[sid,'verified']);
 const venue=await call('chob_add_entity',['venue',{name:'Venue',source_id:sid}]);
 const eid='00000000-0000-4000-8000-000000000020',parent='00000000-0000-4000-8000-000000000021';
 const payload={id:eid,title:'Show',date:'2026-10-07',location:'Legacy venue',location_region:'Bangkok',artist_ids:['00000000-0000-4000-8000-000000000010'],participation_condition:'ticket',status:'published',attributes:{region:'泰国',picture_urls:[],venue_id:venue,field_states:{time:'tba'}}};
 const first=await call('chob_save_event_architecture',[payload,[],null,null,{source_id:sid,is_primary:true}]);assert.equal(first.venue_id,venue);
 const second=await call('chob_save_event_architecture',[{...payload,date:'2026-10-08'},[],first.updated_at,null,{source_id:sid2}]);
 const history=(await db.query("select * from event_changes where event_id=$1 and field='date' order by changed_at desc",[eid])).rows;
 assert.equal(history[0].source_id,sid2);assert.equal(history[0].old_value,'2026-10-07');assert.equal(history[0].new_value,'2026-10-08');
 await assert.rejects(()=>call('chob_save_event_architecture',[payload,[],first.updated_at,null,{source_id:sid}]),/被修改/);
 await call('chob_save_event_architecture',[{...payload,id:parent,title:'Parent',attributes:{...payload.attributes,field_states:{}}},[],null,null,{}]);
 const child=await call('chob_save_event_architecture',[{...payload,date:'2026-10-08',attributes:{...payload.attributes,parent_event_id:parent}},[],second.updated_at,null,{source_id:sid}]);
 const p=(await db.query('select updated_at::text from events where id=$1',[parent])).rows[0];
 await assert.rejects(()=>call('chob_save_event_architecture',[{...payload,id:parent,attributes:{...payload.attributes,parent_event_id:eid}},[],p.updated_at,null,{source_id:sid}]),/循环/);
 const reviews=await call('chob_add_entity_review',[{entity_type:'artist',source_id:sid,reason:'ambiguous aliases'}]);await call('chob_resolve_entity_review',[reviews,'rejected','No reliable identity']);
 await assert.rejects(()=>call('chob_resolve_entity_review',[reviews,'resolved','Retry']),/已处理/);
 await as(null,'anon');const feed=await call('chob_public_feed');const row=feed.records.find(r=>r.id===eid);assert.equal(row.venue_entity.name,'Venue');assert.equal(row.parent_event.id,parent);assert.equal(row.sources.length,2);assert.equal(row.sources[0].raw_evidence,undefined);assert.equal(row.sources[0].created_by,undefined);
 await assert.rejects(()=>db.query('select * from sources'),/permission denied/);await assert.rejects(()=>call('chob_public_feed_legacy034'),/permission denied/);
 await as(fan);await assert.rejects(()=>call('chob_add_source',[source]),/Web/);
 await as(admin);await db.exec("select set_config('test.wechat','true',false)");await assert.rejects(()=>call('chob_add_source',[source]),/Web/);
 assert.equal((await db.query('select * from sources')).rows.length,0);
 await db.exec("select set_config('test.wechat','false',false)");
 await assert.rejects(()=>db.query("update sources set raw_evidence='{}'"),/permission denied/);
 assert.equal(child.location,'Legacy venue');
 const undated={...payload,id:'00000000-0000-4000-8000-000000000022',date:'',artist_ids:[],location:'',attributes:{region:'泰国',picture_urls:[],field_states:{date:'tba',location:'tba',artist_ids:'tba'}}};
 await assert.rejects(()=>call('chob_save_event_architecture',[undated,[],null,null,{}]),/证据/);
 const unknown=await call('chob_save_event_architecture',[undated,[],null,null,{source_id:sid}]);assert.equal(unknown.date,null);assert.deepEqual(unknown.artist_ids,[]);
 const duplicate=await call('chob_save_event_architecture',[{...payload,id:'00000000-0000-4000-8000-000000000024',attributes:{region:'泰国',picture_urls:[]}},[],null,null,{source_id:sid2}]);
 await call('chob_review_duplicates',[[unknown.id,duplicate.id],unknown.id,'merge']);
 assert.equal((await db.query('select * from event_sources where event_id=$1',[unknown.id])).rows.length,2);
 const afterMerge=(await db.query('select updated_at::text from events where id=$1',[unknown.id])).rows[0].updated_at;
 unknown.updated_at=afterMerge;
 const review=await call('chob_add_entity_review',[{entity_type:'event',event_id:unknown.id,source_id:sid,reason:'possible duplicate'}]);
 await assert.rejects(()=>call('chob_save_event_architecture',[undated,[],unknown.updated_at,null,{source_id:sid}]),/异常/);
 await call('chob_resolve_entity_review',[review,'resolved','Confirmed separate event']);
 const task={id:'00000000-0000-4000-8000-000000000030',title:'Ticket',task_type:'ticketing',status:'draft',start_date:'2026-10-01',end_date:'2026-10-06'};
 const t1=await call('chob_save_event_architecture',[{...undated,status:'draft'},[task],unknown.updated_at,null,{source_id:sid}]);
 await call('chob_save_event_architecture',[{...undated,status:'draft'},[{...task,end_date:'2026-10-07'}],t1.updated_at,null,{source_id:sid}]);
 assert.equal((await db.query("select source_id from event_changes where field=$1 and old_value is not null",['task:'+task.id+':end_date'])).rows[0].source_id,sid);
 await db.exec('reset role');
 await db.query("update events set status='draft',attributes=attributes||jsonb_build_object('admin_deleted_at',now()) where id=$1",[eid]);
 await db.query("update events set trash_expires_at=now()-interval '1 day' where id=$1",[eid]);
 await db.exec('select chob_private.purge_event_trash()');assert.equal((await db.query('select id from events where id=$1',[eid])).rows.length,1);
 await as(null,'anon');assert.equal((await call('chob_public_feed')).records.some(r=>r.id===eid),false);

 await as(admin);
 const aid=await call('chob_save_source_account',[{platform:'x',account:'official',url:'https://x.com/official',source_type:'organizer',enabled:true,reviewed:true,start_at:'2026-10-01T00:00:00Z',notes:'Organizer role manually verified'}]);
 const scan=await call('chob_claim_scan',[aid]);assert.equal(scan.cursor,null);assert.equal(await call('chob_claim_scan',[aid]),null);
 await call('chob_checkpoint_scan',[scan.id,{post:'10'},{fetched:10},null,false]);
 await call('chob_checkpoint_scan',[scan.id,null,{fetched:11,failed:1},'Partial failure',true]);
 assert.deepEqual((await db.query('select cursor from source_accounts where id=$1',[aid])).rows[0].cursor,{post:'10'});
 const scan2=await call('chob_claim_scan',[aid]);assert.deepEqual(scan2.cursor,{post:'10'});
 await call('chob_checkpoint_scan',[scan2.id,null,{fetched:0},null,true]);
 const asid=await call('chob_add_source',[{url:'https://x.com/official/status/10',platform:'x',account:'official',source_type:'organizer',priority:1,raw_evidence:{text:'Show'}}]);
 const aeid='00000000-0000-4000-8000-000000000050';
 const bundle={...payload,id:aeid,title:'Automation show',date:'2026-10-10',attributes:{region:'thailand',picture_urls:[]}};
 const hash='a'.repeat(64);
 const auto=await call('chob_commit_automation',[aid,'10',hash,asid,'created',bundle,[],null,null,null,null]);assert.equal(auto.action,'created');
 const repeat=await call('chob_commit_automation',[aid,'10',hash,asid,'created',bundle,[],null,null,null,null]);assert.equal(repeat.action,'duplicate');
 const existing=(await db.query('select updated_at::text from events where id=$1',[aeid])).rows[0].updated_at;
 const notice={title:'Changed',body:'18:00 → 19:00',source_url:'https://x.com/official/status/11'};
 const updated=await call('chob_commit_automation',[aid,'11','b'.repeat(64),asid,'updated',{...bundle,time:'19:00'},[],existing,notice,null,null]);assert.equal(updated.action,'updated');
 await call('chob_commit_automation',[aid,'11','b'.repeat(64),asid,'updated',{...bundle,time:'19:00'},[],existing,notice,null,null]);
 assert.equal((await db.query('select count(*)::int as n from chob_announcements where event_id=$1',[aeid])).rows[0].n,1);
 const nowVersion=(await db.query('select updated_at::text from events where id=$1',[aeid])).rows[0].updated_at;
 await assert.rejects(()=>call('chob_commit_automation',[aid,'12','c'.repeat(64),asid,'updated',{...bundle,time:'20:00'},[],nowVersion,{title:''},null,null]),/标题/);
 assert.equal((await db.query('select time::text from events where id=$1',[aeid])).rows[0].time,'19:00:00');
 assert.equal((await db.query("select count(*)::int as n from automation_receipts where post_id='12'")).rows[0].n,0);
 assert.equal((await db.query('select count(*)::int as n from chob_announcements where event_id=$1',[aeid])).rows[0].n,1);
 const q=await call('chob_commit_automation',[aid,'13','d'.repeat(64),asid,'review',null,[],null,null,{entity_type:'event',event_id:aeid,reason:'Unknown artist',evidence:{raw:{text:'Show'},translations:{zh:'中文'}}},null]);
 await assert.rejects(()=>call('chob_apply_automation_review',[q.reviewId,{...bundle,title:''},[],nowVersion,'Reviewed']),/标题/);
 assert.equal((await db.query('select status from entity_reviews where id=$1',[q.reviewId])).rows[0].status,'pending');
 await call('chob_apply_automation_review',[q.reviewId,{...bundle,time:'20:00'},[],nowVersion,'Official update confirmed']);
 assert.equal((await db.query('select status from entity_reviews where id=$1',[q.reviewId])).rows[0].status,'resolved');
 await assert.rejects(()=>call('chob_apply_automation_review',[q.reviewId,bundle,[],null,'Duplicate']),/pending/);
 await call('chob_commit_automation',[aid,'14','e'.repeat(64),asid,'content',null,[],null,null,null,{kind:'trailer',facts:{title:'MV'},translations:{zh:'预告'}}]);
 assert.equal((await db.query('select count(*)::int as n from source_contents')).rows[0].n,1);
 await as(fan);await assert.rejects(()=>call('chob_claim_scan',[aid]),/Web/);
 await as(admin);await db.exec("select set_config('test.wechat','true',false)");await assert.rejects(()=>call('chob_claim_scan',[aid]),/Web/);await db.exec("select set_config('test.wechat','false',false)");
 await as(null,'anon');await assert.rejects(()=>db.query('select * from automation_receipts'),/permission denied/);await assert.rejects(()=>db.query('select * from source_accounts'),/permission denied/);

 } finally {await db.close()}
});
